import './main.scss';
import './js/components/refs';
import './js/components/apiService';
import './js/components/header';
import './js/components/scrollToTopBtn.js';
import './js/components/handleSignup';
import './js/components/my-lib';
import './js/composables/mainCards';
import './js/components/modal.js';
